### ISSUE TITLE
Configurable filename

### ISSUE THREAD

**Issue by jn64** [monferrand/mzettel#2]
Hi, thank you for the extension. I'm using it to take notes with zettelkasten method.

I would like to use more specific timestamp in the filename (date and time instead of just date). For example `202005112359_title` not `20200511_title`.

**Comment by monferrand** [comment]
Hi!
Indeed, that could be useful. I will work on it.

**Comment by monferrand** [comment]
The latest version should add this feature

**Comment by jn64** [comment]
Thank you! :smile:
